const fs = require('fs')
const path = require('path')
const { spawnSync } = require('child_process')
const { createQueue, parseQueueInputLine } = require('../queue/urlQueue')

const urlOnlyQueue = createQueue(['https://example.com'])
assert(urlOnlyQueue[0].url === 'https://example.com', 'URL-only queue inputs should still work')
assert(urlOnlyQueue[0].businessName === '', 'URL-only inputs should have empty businessName')
const namedInput = parseQueueInputLine('Example Clinic | https://example-clinic.no')
const namedQueue = createQueue([namedInput])
assert(namedQueue[0].businessName === 'Example Clinic', 'Business Name | URL handoff should preserve businessName')
assert(namedQueue[0].url === 'https://example-clinic.no', 'Business Name | URL handoff should preserve URL')
const jsonQueue = createQueue([parseQueueInputLine('{"url":"https://json-clinic.no","businessName":"JSON Clinic","industry":"dentists","location":"Halden"}')])
assert(jsonQueue[0].businessName === 'JSON Clinic', 'JSONL handoff should preserve businessName')
assert(jsonQueue[0].industry === 'dentists', 'JSONL handoff should preserve industry')
assert(jsonQueue[0].location === 'Halden', 'JSONL handoff should preserve location')

const runs = path.join(__dirname, 'runs-smoke')
fs.rmSync(runs, { recursive: true, force: true })
const result = spawnSync(process.execPath, ['cli/run-audit-queue.js', '--urls', 'http://127.0.0.1:5173', '--runs', runs, '--retries', '1'], { cwd: path.join(__dirname, '..'), encoding: 'utf8' })
if (result.status !== 0) { console.error(result.stdout); console.error(result.stderr); process.exit(result.status) }
const payload = JSON.parse(result.stdout)
assert(payload.totalItems === 1, 'one queue item should be processed')
assert(payload.completedItems === 1, 'one queue item should complete')
assert(fs.existsSync(payload.statePath), 'state file should exist')
assert(fs.existsSync(payload.summaryPath), 'summary file should exist')
assert(fs.existsSync(payload.reportSurfaces.markdownPath), 'markdown report surface should exist')
assert(fs.existsSync(payload.reportSurfaces.htmlPath), 'html report surface should exist')
assert(fs.existsSync(payload.reportSurfaces.csvPath), 'csv report surface should exist')
assert(fs.existsSync(payload.reviewWorkspace.indexPath), 'review workspace index should exist')
assert(fs.existsSync(payload.reviewWorkspace.reviewStatusPath), 'review status should exist')
assert(fs.existsSync(payload.reviewWorkspace.selectedLeadsPath), 'selected leads export should exist')
assert(fs.existsSync(payload.reviewWorkspace.crmShortlistedPath), 'CRM shortlisted export should exist')
const summary = JSON.parse(fs.readFileSync(payload.summaryPath, 'utf8'))
assert(summary.results[0].status === 'completed', 'summary item should be completed')
assert(fs.existsSync(summary.results[0].reportPath), 'worker report should exist')
function assert(condition, message) { if (!condition) throw new Error(message) }
